### PR TITLE
Make it searchable for Kanji outside WaniKani

### PR DESCRIPTION
**Pull request by patarapolw**
Mentioned here: https://community.wanikani.com/t/userscript-keisei-%E5%BD%A2%E5%A3%B0-semantic-phonetic-composition/21479/373

I have no idea how to make a good UI, however.

Furthermore, many Kanji, such as 繋 in 繋がり, aren't in the database.

### CODE REVIEW

**Comment by mwil** [comment]
I can't really check if he changes work, please send in fixes if there is a problem.

**Comment by mwil** [comment]
Oh one more thing, to roll out the new release you need to update the version number and the URLs to the latest version of the included source files you want to use, for example in `wk_keisei.user.js` for Keisei.

If you want to add more kanji, the data comes from the JSON files in the `db` directory.

**Comment by patarapolw** [comment]
About the looks (Click and edit. They are inconspicuous text inputs.):

- Keisei

image

- Niai

image

I am not sure about adding entries to JSON files. Do they need to be compiled somehow?

**Comment by Sinyaven** [comment]
@patarapolw I'm a bit curious why you decided to place the text input for Keisei in the section heading, but the text input for Niai in the settings dialog? Was there a problem with adding the text input to the section heading in Niai?

And I noticed that for radicals, the text input is empty so that the heading is just "Phonetic-Semantic Composition of ". The easiest solution would probably be to remove your search feature when the section is for a radical? Because I think it would be difficult to make the text box display image-based radicals, so it's probably best to limit the feature to kanji sections?

**Comment by patarapolw** [comment]
> Keisei in the section heading

I am not sure why, but Keisei section heading is always `h3`, despite being `h2` in the code.

https://github.com/mwil/wanikani-userscripts/blob/afe491130e4e65af2b6aa22b57b24024238ba44e/wanikani-phonetic-compounds/wk_keisei.html.js#L90

image

**Comment by patarapolw** [comment]
> to roll out the new release you need to update the version number

Commithash? I am not sure I can know that before PR is completed.

**Comment by mwil** [comment]
I already merged this PR, so the commits should already be in place. For the databases, the kanji need to be escaped and minimized, the script is at https://github.com/mwil/wanikani-userscripts/blob/master/wanikani-phonetic-compounds/db/gen_esc.sh

That uses https://stedolan.github.io/jq/

**Comment by Sinyaven** [comment]
@patarapolw
>I am not sure why, but Keisei section heading is always h3, despite being h2 in the code.

That is because after some WK changes, the original injection methods of Niai and Keisei were broken and I switched their injection method to my [Item Info Injector library script](https://community.wanikani.com/t/53823) which takes the heading elements and the section content elements as two separate arguments. I was a bit lazy and did not want to change too much of the existing code, so I just extract the child nodes from the `h2` element when passing it on to Item Info Injector:
https://github.com/mwil/wanikani-userscripts/blob/afe491130e4e65af2b6aa22b57b24024238ba44e/wanikani-phonetic-compounds/wk_keisei.main.js#L55

The library script decides which heading is the correct one for the current page. On kanji item pages, WK uses `h3` for subsections (and I inject Keisei as a subsection of WaniKani's "Reading" section because of its close relation to the kanji reading), while during lessons and reviews, WK uses `h2` for subsections.

**Comment by patarapolw** [comment]
@Sinyaven Should I change it `injectorState.injector.append(...)`? Will it have undesired effects on review pages?

**Comment by Sinyaven** [comment]
Is there a problem with the current behavior? Your feature seems to work with `h3` without a problem. I was more wondering why Niai does not do the same as Keisei (adding the input box in the heading instead of the settings dialog).

EDIT: Furthermore, if you change it from `appendSubsection()` to `append()`, the heading will be in a `button` during the lesson quiz, because in WaniKani's new accordion layout, subsections are `h2` while sections are `button`. Niai already uses `append()` (because in my opinion, it does not really belong into any of the default WK sections) and as a result looks like this:

image

**Comment by patarapolw** [comment]
> Your feature seems to work with `h3` without a problem. I was more wondering why Niai does not do the same as Keisei (adding the input box in the heading instead of the settings dialog).

@Sinyaven They are all design decisions, but it can be made selective to itemPage anyway, with

```js
        const appender = (injectorState.on === 'itemPage' ? injectorState.injector.append : injectorState.injector.appendSubsection);
        let section = appender([...keiseiSection[0].childNodes], [keiseiSection[1], keiseiSection[2]], {injectImmediately: true});
```

As for when I add input box to the modal, I have to force modal width to `650px` or more. The default is `560px` for some reasons. Otherwise, "for ..." would drop to the second line.

```js
    WK_Keisei.prototype.injectModals = function()
    {
        const $settings_modal = $(`<div></div>`)
                                .attr(`id`, `keisei_modal_settings`)
                                .css('width', '650px')
```

**Comment by Sinyaven** [comment]
Yes, if you want you can let Keisei be a main section on the item page but a subsection everywhere else. Is there a technical reason that you want it to be `h2` or do you prefer it visually?

**Comment by patarapolw** [comment]
Yeah, just visual preference (of consistency).

> EDIT: Furthermore, if you change it from `appendSubsection()` to `append()`, the heading will be in a `button` during the lesson quiz, because in WaniKani's new accordion layout, subsections are `h2` while sections are `button`. Niai already uses `append()` (because in my opinion, it does not really belong into any of the default WK sections) and as a result looks like this:

I don't understand a thing (and I don't normally do reviews).

image

After all as `.append()`

image

Maybe now I understand a little, but I still don't know about Accordion layout.

**Comment by Sinyaven** [comment]
WaniKani introduced the accordion layout for the lesson quiz a few months ago. To see it, you have to make sure script compatibility mode is disabled, do a lesson batch, and start the quiz that immediately follows the lessons.

And as I have said before, I see Keisei as a subsection belonging to the "Reading" section of WaniKani, but Niai as its own main section (same as the "Visually Similar Kanji" section in vanilla WK), so they are styled differently as a consequence. But I don't feel very strongly about this, so Keisei can also be changed to its own main section. The biggest difference will be in the accordion layout -- whether Keisei will be in its own collapsible section or part of the "Reading" section.

**Comment by patarapolw** [comment]
> I see Keisei as a subsection belonging to the "Reading" section of WaniKani, but Niai as its own main section

If so, probably `h3` is already OK for the sake of semantics.

**Pull request merged**
